### ISSUE TITLE
学习Rust

### ISSUE THREAD

**Issue by jnj1** [iamafool/iamafool.github.io#4]
[The Rust Programming Language](https://doc.rust-lang.org/book/)

**Comment by sashelper** [comment]
1. Getting Started
1.1. Installation
1.2. Hello, World!
1.3. Hello, Cargo!
2. Programming a Guessing Game
3. Common Programming Concepts
3.1. Variables and Mutability
3.2. Data Types
3.3. Functions
3.4. Comments
3.5. Control Flow
4. Understanding Ownership
4.1. What is Ownership?
4.2. References and Borrowing
4.3. The Slice Type

**Comment by sashelper** [comment]
5. Using Structs to Structure Related Data
5.1. Defining and Instantiating Structs
5.2. An Example Program Using Structs
5.3. Method Syntax

**Comment by sashelper** [comment]
6. Enums and Pattern Matching
6.1. Defining an Enum
6.2. The match Control Flow Operator
6.3. Concise Control Flow with if let

**Comment by sashelper** [comment]
7. Managing Growing Projects with Packages, Crates, and Modules
7.1. Packages and Crates
7.2. Defining Modules to Control Scope and Privacy
7.3. Paths for Referring to an Item in the Module Tree
7.4. Bringing Paths Into Scope with the use Keyword
7.5. Separating Modules into Different Files

**Comment by sashelper** [comment]
8. Common Collections
    8.1 Storing Lists of Values with Vectors

**Comment by sashelper** [comment]
8.2 Storing UTF-8 Encoded Test with Strings

**Comment by sashelper** [comment]
8.3 Storing Keys with Associated Values in Hash Maps

**Comment by sashelper** [comment]
9. Error Handling
    9.1 Unrecoverable Errors with panic!

**Comment by sashelper** [comment]
9.2 Recoverable Errors with Result

**Comment by sashelper** [comment]
9.3 To panic! or Not To panic!

**Comment by sashelper** [comment]
10. Generic Types, Traits, and Lifetimes

**Comment by sashelper** [comment]
10.1 Generic Data Types

**Comment by sashelper** [comment]
10.2 Traits: Defining Shared Behavior

**Comment by sashelper** [comment]
10.3 Validating References with Lifetimes
        Preventing Dangling References with Lifetimes
       The Borrow Checker
       Generic Lifetimes in Functions
       Lifetime Annotation Syntax
       Lifetime Annotations in Function Signatures

**Comment by sashelper** [comment]
Thinking in Terms of Lifetimes
Lifetime Annotations in Struct Definitions
Lifetime Elision
Lifetime annotations in Method Definitions
The Static Lifetime
Generic Type Parameters, Trait Bounds, and Lifetimes Together
Summary

**Comment by sashelper** [comment]
11. Writing Automated Tests
     11.1 How to Write Tests

**Comment by sashelper** [comment]
11.2 Controlling How Tests Are Run
11.3 Test Organization

**Comment by sashelper** [comment]
12 An I/O Project: Building a Command Line Program
     12.1 Accepting Command Line Arguments

**Comment by sashelper** [comment]
12.3 Refactoring to Improve Modularity and Error Handling

**Comment by sashelper** [comment]
12.4 Developing the Library's Functionality with Test Driven Development

**Comment by sashelper** [comment]
12.5 Working with Environment Variables

**Comment by sashelper** [comment]
12.6 Writing Error Messages to Standard Error Instead of Standard Output

**Comment by sashelper** [comment]
13. Functional Language Features: Iterators and Closures

**Comment by sashelper** [comment]
13.1 Closures: Anonymous Functions that Can Capture Their Environment

**Comment by sashelper** [comment]
13.2 Processing a Series of Items with Iterators
13.3 Improving Our I/O Project
13.4 Comparing Performance: Loops vs. Iterators

**Comment by sashelper** [comment]
14. More about Cargo and Crates.io
14.1 Customizing Builds with Release Profiles
14.2 Publishing a Crate to Crates.io
14.3 Cargo Workspaces
14.4 Installing Binaries from Crates.io with cargo install
14.5 Extending Cargo with Custom Commands

**Comment by sashelper** [comment]
15. Smart Pointers
15.1 Using Box to Point to Data on the Heap
15.2 Treating Smart Pointers Like Regular References with the Deref Trait

**Comment by sashelper** [comment]
15.3 Running Code on Cleanup with the Drop Trait

**Comment by sashelper** [comment]
15.4 Rc, the Reference Counted Smart Pointer

**Comment by sashelper** [comment]
15.5 RefCell and the Interior Mutability Pattern

**Comment by sashelper** [comment]
15.6 References Cycles Can Leak Memory

**Comment by sashelper** [comment]
16. Fearless Concurrency
      16.1 Using Threads to Run Code Simultaneously

**Comment by sashelper** [comment]
16.2 Using Message Passing to Transfer Data Between Threads

**Comment by sashelper** [comment]
16.3 Shared-State Concurrency
16.4 Extensible Concurrency with the Sync and Send Traits

**Comment by sashelper** [comment]
17. Object Oriented Programming Features of Rust
     17.1 Characteristics of Object-Oriented Languages
     17.2 Using Trait Objects That Allow for Values of Different Types

**Comment by sashelper** [comment]
17.3 Implementing an Object-Oriented Design Pattern

**Comment by sashelper** [comment]
18. Patterns and Matching
      18.1 All the Places Patterns Can Be Used

**Comment by sashelper** [comment]
18.2 Refutability: Whether a Pattern Might Fail to Match

**Comment by sashelper** [comment]
18.3 Pattern Syntax

**Comment by sashelper** [comment]
19. Advanced Features
      19.1 Unsafe Rust

**Comment by sashelper** [comment]
19.2 Advanced Traits

**Comment by sashelper** [comment]
19.3 Advanced Types

**Comment by sashelper** [comment]
19.4 Advanced Functions and Closures

**Comment by sashelper** [comment]
19.5 Macros

**Comment by sashelper** [comment]
20. Final Project: Building a Multithreaded Web Server
      20.1 Building a Single-Threaded Web Server

**Comment by sashelper** [comment]
20.2 Turning Our Single-Threaded Server into a Multithreaded Server

**Comment by sashelper** [comment]
20.3 Graceful Shutdown and Cleanup

**Comment by sashelper** [comment]
21. Appendix
